/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.deception.cli;


import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.api.model.Container;
import com.github.dockerjava.core.DockerClientBuilder;
import picocli.CommandLine.Command;

import java.util.List;
import java.util.concurrent.Callable;

@Command(name = "deception-cli", abbreviateSynopsis = true, mixinStandardHelpOptions = true, version = "deception-cli 0.1",
        description = "CLI for DeceptionKit")
public class DeceptionCli implements Callable<Integer> {

    public Integer call() throws Exception {
        try (DockerClient dockerClient = DockerClientBuilder.getInstance().build()) {
            List<Container> containers = dockerClient.listContainersCmd().withShowSize(true).withShowAll(true).exec();
            containers.forEach(container -> System.out.println(container.getNames()[0]));
        }

        return 0;
    }

    public static void main(String[] args) {
        int exitCode = new picocli.CommandLine(new DeceptionCli()).execute(args);
        System.exit(exitCode);
    }


}
