version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
#    image: riccardoob/keycloak-generated
    container_name: keycloak-dev
    ports:
      - "8100:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]
