version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 8100:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
