/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

group = "com.deceptionkit"
version = "1.1.0"

dependencies {
    implementation("info.picocli:picocli:4.7.5")

    implementation("com.github.docker-java:docker-java:3.2.10")

    implementation("org.slf4j:slf4j-nop:2.0.9")

    implementation("com.fasterxml.jackson.core:jackson-core:2.16.0")

//    annotationProcessor("info.picocli:picocli-codegen:4.7.5")

    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

//add compileArgs to compileJava
tasks.withType<JavaCompile> {
//    options.compilerArgs.addAll(listOf("-Aproject=${project.group}/${project.name}"))
}

tasks.register<Copy>("extractTar") {
    dependsOn(tasks.named("distTar"))
    group = "distribution"
    from(tarTree(tasks.named("distTar").get().outputs.files.singleFile))
    into("build/install")
}

application {
    // Define the main class for the application.
    mainClass.set("com.deceptionkit.cli.DeceptionCli")
}
