#!/bin/bash

docker container stop keycloak-dev
docker container rm keycloak-dev

docker compose -f ../keycloak/keycloak-compose.yaml up -d

sleep 15

tar -xf build/distributions/deception-cli-1.0.0.tar -C build/distributions/

build/distributions/deception-cli-1.0.0/bin/deception-cli "$@"
